### ISSUE TITLE
/prbt/joint_states does not publish the velocity and effort values

### ISSUE THREAD

**Issue by ipa-rar** [PilzDE/pilz_robots#180]
### Commit
8b529fe

### Steps to reproduce
rostopic echo /prbt/joint_states 

### Expected behavior
The /prbt/joint_states should publish the position, velocity and effort values of the robot

### Observed behavior
Only the position values are published. The velocity and effort values remains as zero.

### Logfiles
```
---
header: 
  seq: 4641916
  stamp: 
    secs: 1562851379
    nsecs: 611657848
  frame_id: ''
name: [prbt_joint_1, prbt_joint_2, prbt_joint_3, prbt_joint_4, prbt_joint_5, prbt_joint_6]
position: [1.5610224829837283, -0.08478809506188453, 1.1859512267301469, 0.03310889591033243, 0.29941123317962726, -0.8170235294435855]
velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```
